title = "Clara Scherrer  CV"
baseURL = "https://claraschh.github.io/cv_clara/"
theme = "hugo-resume"
languageCode = "fr-fr"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false
defaultContentLanguage = "fr"

[params]
title = "Recherche d'alternance"
address = "Toulouse 31000"
email = "clara-scherrer@orange.fr"
favicon = "/favicon.ico"
firstName = "Clara"
lastName = "Scherrer"
phone = "06 65 58 03 34"
profileImage = "img/photo_cv_clara.jpg"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = false
sections = ["skills","publications","creations"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/lo%C3%AFs-lamoussi%C3%A8re-237068250/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/LoisLamous"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"
    
[[params.handles]]
    name = "Bluesky"
    link = "https://bsky.app/profile/webbinaro.dev"
    icon = "bluesky"

[[params.handles]]
    link = "https://stackoverflow.com/users/82880/eddie"
    name = "Stack Overflow"
    icon = "stack-overflow"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
